spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/space?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.huanyue.spaceuserclient.entity

logging:
  level:
    com:
      huanyue:
        spaceuserclient:
          dao: debug
